version: "3.5"
services:
  portainer:
    restart: always
    image: portainer/portainer:latest
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
      
 volumes:
   portainer_data:
      external: true
      
